version: '3.8'
services:
  app:
    build: .
    container_name: strikepanel_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      DATABASE_URL: "mysql+pymysql://root:password@db/strikepanel_db"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: strikepanel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: strikepanel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
